FROM debian:bookworm-slim AS base

ARG TARGETARCH

ENV GODOT_VERSION "4.7.1"
ENV GODOT_EXPORT_TEMPLATES_DIR "/root/.local/share/godot/export_templates/${GODOT_VERSION}.stable"

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates wget unzip git xz-utils libfontconfig1 && update-ca-certificates

RUN if [ "$TARGETARCH" = "arm64" ]; then \
        GODOT_ARCH="arm64"; \
    else \
        GODOT_ARCH="x86_64"; \
    fi && \
    # Using the standard GitHub release URL ensures deterministic downloads across architectures
    wget -O godot.zip "https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.${GODOT_ARCH}.zip" && \
    unzip godot.zip && \
    mv Godot_v${GODOT_VERSION}-stable_linux.${GODOT_ARCH} /bin/godot && \
    rm -f godot.zip

 RUN mkdir ~/.cache && \
	mkdir -p ~/.config/godot && \
	mkdir -p $GODOT_EXPORT_TEMPLATES_DIR

RUN git clone https://github.com/mist-interactive/godot_export_templates.git godot_export_templates
RUN cd godot_export_templates && \
	tar -xf linux_release_4_7_1.tar.xz && \
	mv linux_release.x86_64 "$GODOT_EXPORT_TEMPLATES_DIR" && \
    mv web_release.zip "$GODOT_EXPORT_TEMPLATES_DIR" && \
    mv web_nothreads_release.zip "$GODOT_EXPORT_TEMPLATES_DIR"

COPY . /root/memoir-3167/


RUN mkdir -p /root/server/
RUN godot --headless --path /root/memoir-3167 --export-release "Linux" "/root/server/memoir-3167.bin"

RUN mkdir /root/game
RUN godot --headless --path /root/memoir-3167 --export-release "Web" "/root/game/index.html"
